packages:
  - apps/*
  - packages/*
catalog:
  "@hono/trpc-server": 0.4.0
  "@tailwindcss/postcss": 4.1.10
  "@tanstack/react-form": 1.12.3
  "@tanstack/react-query": 5.85.5
  "@tanstack/react-query-devtools": 5.85.5
  "@trpc/client": 11.5.0
  "@trpc/server": 11.5.0
  "@trpc/tanstack-react-query": 11.5.0
  "@types/bun": 1.2.6
  "@types/node": "20"
  "@types/react": "19"
  "@types/react-dom": "19"
  better-auth: 1.3.7
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  dotenv: 17.2.1
  drizzle-kit: 0.31.2
  drizzle-orm: 0.44.2
  drizzle-zod: 0.8.3
  hono: 4.8.2
  lucide-react: 0.487.0
  mysql2: 3.14.0
  next: 15.5.0
  next-themes: 0.4.6
  radix-ui: 1.4.2
  react: 19.0.0
  react-dom: 19.0.0
  sonner: 2.0.5
  tailwind-merge: 3.3.1
  tailwindcss: 4.1.10
  tsdown: 0.14.1
  turbo: 2.5.4
  tw-animate-css: 1.3.4
  uuid: 12.0.0
  zod: 4.0.2
